-- Create minimal tables for MVC portfolio pages
-- Run this as a user that owns the schema (e.g. SYSTEM for demo, but prefer a dedicated user).

-- ===== Skills =====
create table tp_skill (
  skill_id number generated by default on null as identity,
  skill_name varchar2(100) not null,
  sort_order number,
  constraint pk_tp_skill primary key (skill_id),
  constraint uq_tp_skill_name unique (skill_name)
);

-- ===== Projects =====
create table tp_project (
  project_id number generated by default on null as identity,
  title varchar2(200) not null,
  stack varchar2(200) not null,
  sort_order number,
  constraint pk_tp_project primary key (project_id)
);

create table tp_project_highlight (
  highlight_id number generated by default on null as identity,
  project_id number not null,
  highlight varchar2(400) not null,
  sort_order number,
  constraint pk_tp_project_highlight primary key (highlight_id),
  constraint fk_tp_project_highlight_project foreign key (project_id) references tp_project(project_id)
);

-- ===== Company Keywords =====
create table tp_company_keyword (
  keyword_id number generated by default on null as identity,
  keyword varchar2(100) not null,
  sort_order number,
  constraint pk_tp_company_keyword primary key (keyword_id),
  constraint uq_tp_company_keyword unique (keyword)
);

-- ===== Company sections (menu + content) =====
create table tp_company_section (
  section_id number generated by default on null as identity,
  category varchar2(100) not null,
  title varchar2(200) not null,
  anchor varchar2(80) not null,
  body varchar2(2000) not null,
  sort_order number,
  constraint pk_tp_company_section primary key (section_id),
  constraint uq_tp_company_section_anchor unique (anchor)
);
